# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list) #one dimentional array denoted by []

array([1, 2, 3])

In [5]:
arr = np.array(my_list) #one dimentional array denoted by []
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat) #two dimentional array denoted by [[]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**arange() function**

In [9]:
np.arange(0,10) #one dimentional array denoted by []

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11) #one dimentional array denoted by []

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2) #one dimentional array denoted by []

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.arange(0,11,3) #one dimentional array denoted by []

array([0, 3, 6, 9])

In [13]:
np.arange(0,12,3) #one dimentional array denoted by []

array([0, 3, 6, 9])

In [14]:
np.arange(0,15,3) #one dimentional array denoted by []

array([ 0,  3,  6,  9, 12])

**zeros() function**

In [15]:
np.zeros(3) #one dimentional array denoted by []

array([0., 0., 0.])

In [16]:
np.zeros((5,5)) #two dimentional array denoted by [[]]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((5,3)) #two dimentional array denoted by [[]]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((2,3)) #two dimentional array denoted by [[]]

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((10,3)) #two dimentional array denoted by [[]]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros((100,3)) #two dimentional array denoted by [[]]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0

In [21]:
np.zeros((1000,3)) #two dimentional array denoted by [[]]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros((10000,10000)) #two dimentional array denoted by [[]]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
np.zeros((100,100)) #two dimentional array denoted by [[]]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

**ones() function**

In [24]:
np.ones(4) #one dimentional array denoted by []

array([1., 1., 1., 1.])

In [25]:
np.ones((3,4)) #two dimentional array denoted by [[]]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**linspace() function**

In [26]:
np.linspace(0,5,10) #one dimentional array denoted by []

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [27]:
np.linspace(0,5,100) #one dimentional array denoted by []

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

**eye() function**

In [28]:
np.eye(5) #two dimentional array denoted by [[]]

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**rand() funtion gives array of numbers from 0 to n**

In [29]:
np.random.rand()

0.47181381817591406

In [30]:
np.random.rand(1) #one dimentional array denoted by []

array([0.50958939])

In [31]:
np.random.rand(2) #one dimentional array denoted by []

array([0.71886784, 0.41215247])

In [32]:
np.random.rand(5) #one dimentional array denoted by []

array([0.68948633, 0.57108438, 0.78886613, 0.39381302, 0.92030953])

In [33]:
np.random.rand(5,5) #two dimentional array denoted by [[]]

array([[0.9026479 , 0.02665757, 0.91781505, 0.0497494 , 0.85922652],
       [0.7981645 , 0.14743623, 0.26848337, 0.00373906, 0.4753315 ],
       [0.15313684, 0.1486823 , 0.05660129, 0.70975417, 0.04565489],
       [0.3185433 , 0.05588012, 0.24073214, 0.49024174, 0.14633861],
       [0.52150968, 0.42647752, 0.1199391 , 0.87993064, 0.83379711]])

**randn() function gives normal distribution around zero**

In [34]:
np.random.randn(2) #one dimentional array denoted by []

array([ 1.54401839, -0.61496517])

In [35]:
np.random.randn(4,4) #two dimentional array denoted by [[]]

array([[-0.67008691, -0.87751234, -0.55261974,  1.00632884],
       [-0.72427714, -0.46387982,  0.98444443,  0.55316478],
       [ 0.7345633 ,  0.04886575,  1.44396647,  0.34630785],
       [ 0.22297653, -1.1402625 ,  0.17596604,  1.64726884]])

In [36]:
np.random.randint(1,100,10) #one dimentional array denoted by []

array([45, 60, 27, 30, 73, 99, 97, 15, 52, 19])

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)

In [40]:
ranarr

array([33,  5, 27, 40, 29, 41, 14, 22, 24, 11])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
ranarr

array([33,  5, 27, 40, 29, 41, 14, 22, 24, 11])

In [43]:
ranarr.max()

41

In [44]:
ranarr.min()

5

In [45]:
ranarr

array([33,  5, 27, 40, 29, 41, 14, 22, 24, 11])

In [46]:
ranarr.argmax()

5

In [47]:
ranarr.argmin()

1

In [48]:
arr.shape

(25,)

In [49]:
arr = arr.reshape(5,5)

In [50]:
arr #two dimentional array denoted by [[]]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr.shape

(5, 5)

In [52]:
arr.dtype

dtype('int32')

In [53]:
from numpy.random import randint

In [54]:
randint(2,10)

2

# NumPy Indexing and Selection

In [55]:
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[8]

8

In [126]:
arr[1:5]

array([1, 2, 3, 4])

In [127]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [128]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [129]:
arr[:-5]

array([0, 1, 2, 3, 4, 5])

In [130]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [131]:
arr[0:5] = 100

In [132]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [133]:
arr = np.arange(0,11)

In [134]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
slice_of_arr = arr[0:6]

In [136]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [137]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [138]:
slice_of_arr[:] = 99

In [139]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [140]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [141]:
arr_copy = arr.copy()

In [142]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [143]:
arr_copy[:]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [144]:
arr_copy[:] = 100

In [145]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [146]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [147]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [148]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [149]:
arr_2d #two dimentional array denoted by [[]]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [150]:
arr_2d[0][0]

5

In [151]:
arr_2d[0]

array([ 5, 10, 15])

In [152]:
arr_2d[1][1]

25

In [153]:
arr_2d[2][2]

45

In [154]:
arr_2d[1][2]

30

In [155]:
arr_2d[2][1]

40

In [156]:
arr_2d[2,1]

40

In [157]:
arr_2d[1,2]

30

In [158]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [159]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [160]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [161]:
arr = np.arange(1,11)

In [162]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [164]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [165]:
bool_arr = arr > 5

In [166]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [167]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [168]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [169]:
arr[arr < 3]

array([1, 2])

In [170]:
arr_2d = np.arange(50).reshape(5,10)

In [171]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [172]:
arr_2d[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [173]:
arr_2d[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [174]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [175]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# NumPy Operations

Array with Array

Array with Scalars

Universal Array Functions

In [176]:
arr = np.arange(0,11)

In [177]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [178]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [179]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [180]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [181]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [182]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [183]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [184]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [185]:
arr/arr

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [186]:
1/arr

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [187]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [188]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [189]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [190]:
np.max(arr)

10

In [191]:
arr.max()

10

In [192]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [193]:
np.log(arr)

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# NumPy Exercises
Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks,
and then you'll be asked some more complicated questions.

# Import NumPy as np

In [194]:
import numpy as np

**Create an array of 10 zeros**

In [195]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Create an array of 10 ones**

In [196]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Create an array of 10 fives**

In [199]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [200]:
arr[:] = 5

In [201]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [203]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [204]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Create an array of the integers from 10 to 50**

In [205]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Create an array of all the even integers from 10 to 50**

In [206]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create a 3x3 matrix with values ranging from 0 to 8**

In [207]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [208]:
a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Create a 3x3 identity matrix**

In [209]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Use NumPy to generate a random number between 0 and 1**

In [210]:
np.random.rand(1)

array([0.85432481])

**Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution**


In [211]:
np.random.randn(25)

array([ 0.76616295,  0.46318019,  1.16153863, -0.58112323, -0.29114659,
        0.80361591, -0.6052092 , -0.04604773, -1.94325228,  0.57638264,
       -1.59942818, -0.46980327, -0.61588978,  0.12655702,  0.79869759,
        1.52580476, -1.07231464, -0.73122666,  0.88159614, -1.10455145,
        0.35416521,  0.15168152,  0.78432829, -1.79275011,  0.69455031])

In [212]:
np.random.randn(25).shape

(25,)

**Create the following matrix:**

In [213]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [214]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [216]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [218]:
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [219]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**Create an array of 20 linearly spaced points between 0 and 1:**

In [220]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection
Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [221]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [222]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [223]:
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [224]:
mat[2:,:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [225]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

**Now do the following
Get the sum of all the values in mat**

In [228]:
mat[3,4]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [229]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [238]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [243]:
#array([21, 22, 23, 24, 25])

In [244]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [245]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [247]:
mat[-1,:]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])


In [246]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [248]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Get the standard deviation of the values in mat**

In [249]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [250]:
mat.std()

7.211102550927978

In [254]:
np.std(mat)

7.211102550927978

**Get the sum of all the columns in mat**

In [251]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [252]:
mat.sum()

325

In [253]:
np.sum(mat)

325

**Get the sum of all the columns in mat**

In [258]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])