# numpy exercises
A joint effort of the numpy community
The goal is both to offer a quick reference for new and old users and to providealso a set of exercices for those who teach.
If you remember having asked oranswered a (short) problem, you can send a pull request. 
The format is:
#. Find indices of non-zero elements from [1,2,0,0,4,0]
.. code:: python      
        # Author: Somebody     
        print(np.nonzero([1,2,0,0,4,0]))Here is what the page looks like so far:http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.htmlRepository is at: https://github.com/rougier/numpy­100Thanks to Michiaki Ariga, there is now a Julia version.
                       

In [1]:
#1. Import the numpy package under the name np (★☆☆) 
import numpy as np

In [3]:
#2. Print the numpy version and the configuration (★☆☆)
print(np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [4]:
#3. Create a null vector of size 10 (★☆☆)
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [61]:
#4. How to get the documentation of the numpy add function from the commandline? (★☆☆)
#python -c "import numpy; numpy.info(numpy.add)"

In [7]:
#5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#6. Create a vector with values ranging from 10 to 49 (★☆☆)
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#7. Reverse a vector (first element becomes last) (★☆☆)
Z = np.arange(50)
Z = Z[::-1]

In [10]:
#8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#9. Find indices of non­zero elements from [1,2,0,0,4,0] (★☆☆)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [13]:
#10. Create a 3x3 identity matrix (★☆☆)
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#11. Create a 3x3x3 array with random values (★☆☆)
Z = np.random.random((3,3,3))
print(Z)

[[[0.23662687 0.18872171 0.12339821]
  [0.57630268 0.01495411 0.31488181]
  [0.53930508 0.48335842 0.74894765]]

 [[0.04471176 0.65636827 0.42822382]
  [0.53210811 0.60827796 0.68260539]
  [0.95729994 0.77110503 0.68060824]]

 [[0.97825546 0.67576206 0.67592179]
  [0.93131052 0.13102964 0.06187632]
  [0.2087487  0.42889664 0.52153036]]]


In [15]:
#12. Create a 10x10 array with random values and find the minimum and maximumvalues (★☆☆)
Z = np.random.random((10,10))
Zmin,Zmax = Z.min(),Z.max()
print(Zmin,Zmax)

0.008439926844244883 0.9794460855631003


In [16]:
#13. Create a random vector of size 30 and find the mean value (★☆☆)
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4992463894313142


In [17]:
#14. Create a 2d array with 1 on the border and 0 inside (★☆☆)
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0

In [18]:
#15. What is the result of the following expression? (★☆☆)
0*np.nan
np.nan == np.nan
np.inf>np.nan
np.nan-np.nan
0.3 == 3*0.1

False

In [19]:
#16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [23]:
#17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
#18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [22]:
#19. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [162]:
#20. Normalize a 5x5 random matrix (★☆☆)
Z = np.random.random((5,5))
Zmax,Zmin = Z.max(),Z.min()
Z = (Z-Zmin)/(Zmax-Zmin)
print(Z)

[[0.28607083 0.20141935 0.24932898 0.49056162 0.87663891]
 [0.2758539  0.32041917 0.         0.45196631 0.67920654]
 [0.39264614 0.67958542 0.68104983 0.16981269 0.51886507]
 [0.31875736 0.93388535 0.81072521 0.22700333 1.        ]
 [0.16328969 0.00327262 0.9915005  0.55304053 0.69793191]]


In [26]:
#21. Create a custom dtype that describes a color as four unisgned bytes (RGBA)(★☆☆)
color = np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])

D:\anaconda\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [163]:
#22. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
Z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [164]:
#23. Given a 1D array, negate all elements which are between 3 and 8, in place.(★☆☆)
# Author: Evgeni Burovski
Z = np.arange(11)
Z[(3<Z)&(Z<=8)]*=-1

In [166]:
#24. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas
from numpy import*
print(sum(range(5),-1))

10


In [60]:
#25. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
#Z**Z
#2<<Z>>2
#Z<-Z
#1j*Z
#Z/1/1
#Z<Z>Z

In [167]:
#26. What are the result of the following expressions?
np.array(0)//np.array(0)
np.array(0)//np.array(0.)
np.array(0)/np.array(0)
np.array(0)/np.array(0.)

D:\anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  
D:\anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until
D:\anaconda\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.
D:\anaconda\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


nan

In [168]:
#27. How to round away from zero a float array ? (★☆☆)
# Author: Charles R Harris
Z = np.random.uniform(-10,+10,10)
print(np.trunc(Z+np.copysign(0.5,Z)))

[ 4. -4.  8.  5. -6. -2. 10.  4.  4. -7.]


In [169]:
#28. Extract the integer part of a random array using 5 different methods (★★☆)
Z = np.random.uniform(0,10,10)
print(Z-Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[4. 6. 9. 5. 5. 2. 7. 2. 2. 5.]
[4. 6. 9. 5. 5. 2. 7. 2. 2. 5.]
[4. 6. 9. 5. 5. 2. 7. 2. 2. 5.]
[4 6 9 5 5 2 7 2 2 5]
[4. 6. 9. 5. 5. 2. 7. 2. 2. 5.]


In [170]:
#29. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
Z = np.zeros((5,5))
Z+= np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [171]:
#30. Consider a generator function that generates 10 integers and use it to build anarray (★☆☆)
#def generate():
 #   for x in xrange(10):
#        yield x
#Z=np.fromiter(generate(),dtype=float,count=-1)
#print(Z)   

In [172]:
#31. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)      

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [173]:
#32. Create a random vector of size 10 and sort it (★★☆)
Z = np.random.random(10)
Z.sort()
print(Z)       

[0.02358363 0.21074487 0.30274654 0.36654083 0.4803157  0.61516762
 0.7022566  0.83065336 0.86045505 0.92951049]


In [174]:
#33. How to sum a small array faster than np.sum? (★★☆)# Author: Evgeni Burovski
Z = np.arange(10)
np.add.reduce(Z)     

45

In [175]:
#34. Consider two random array A anb B, check if they are equal (★★☆)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal) 

False


In [176]:
#35. Make an array immutable (read­only) (★★☆)
Z = np.zeros(10)
Z.flags.writeable = False
Z[0]

0.0

In [177]:
#36. Consider a random 10x2 matrix representing cartesian coordinates, convert themto polar coordinates (★★☆)
Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)      

[0.70168058 0.61005118 0.19234129 0.88184922 0.88542234 0.52972228
 1.06773792 0.67341631 0.64323783 1.03115355]
[0.72401381 1.28599379 1.02885136 0.63445015 0.74930439 0.68838811
 0.99644304 0.37156746 0.68353535 1.30798075]


In [178]:
#37. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)      

[0.56761659 0.4255427  0.64862186 0.63991228 0.04107728 0.
 0.24675217 0.94636607 0.74859105 0.22628025]


In [180]:
#38. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area(★★☆
Z = np.zeros((10,10),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [181]:
#39. Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi ­ yj))# Author: Evgeni Burovski
X = np.arange(8)
Y = X+0.5
C = 1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


In [182]:
#40. Print the minimum and maximum representable value for each numpy scalar type(★★☆)
for dtype in[np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in[np.float32,np.float64]:
        print(np.finfo(dtype).min)
        print(np.finfo(dtype).max)
        print(np.finfo(dtype).eps)  

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [183]:
#41. How to print all the values of an array? (★★☆)
#np.set_printoptions(threshold=np.nan)
#Z=np.zeros((25,25))
#print(Z)    

In [184]:
#42. How to find the closest value (to a given scalar) in an array? (★★☆)
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])       

54


In [185]:
#43. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
Z = np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
print(Z)     

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [186]:
#44. Consider a random vector with shape (100,2) representing coordinates, find pointby point distances (★★☆)
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]),np.atleast_2d(Z[:,1])
D = np.sqrt((X-X.T)**2+(Y-Y.T)**2)
print(D)
# Much faster with scipyimportscipy# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.83012744 0.89207648 0.6405638  0.17285385 0.65903824
  0.34939168 1.05376047 0.61136186 0.64532325]
 [0.83012744 0.         0.62296862 0.534034   0.71151745 0.31837799
  0.73806429 0.41622602 0.3727063  0.24681521]
 [0.89207648 0.62296862 0.         0.25315706 0.71922275 0.83594527
  0.57769955 0.38237572 0.36169806 0.7434744 ]
 [0.6405638  0.534034   0.25315706 0.         0.46787229 0.65932385
  0.34526786 0.48967215 0.17217669 0.57248186]
 [0.17285385 0.71151745 0.71922275 0.46787229 0.         0.60086539
  0.19700828 0.89393782 0.44977877 0.56421498]
 [0.65903824 0.31837799 0.83594527 0.65932385 0.60086539 0.
  0.71052138 0.72215079 0.49190543 0.09292118]
 [0.34939168 0.73806429 0.57769955 0.34526786 0.19700828 0.71052138
  0.         0.82276808 0.4001542  0.65232933]
 [1.05376047 0.41622602 0.38237572 0.48967215 0.89393782 0.72215079
  0.82276808 0.         0.44415905 0.63684678]
 [0.61136186 0.3727063  0.36169806 0.17217669 0.44977877 0.49190543
  0.4001542  0.44415

In [188]:
#45. How to convert a float (32 bits) array into an integer (32 bits) in place?

Z = np.arange(10,dtype=np.int32)
Z = Z.astype(np.float32,copy=False)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [189]:
#46. How to read the following file? (★★☆)# File content:# -------------1,2,3,4,56,,,7,8,,9,10,11# -------------


#Z=np.genfromtxt("missing.dat",delimiter=",")

In [190]:
#Z=np.genfromtxt("missing.dat",delimiter=",")

In [191]:
#47. What is the equivalent of enumerate for numpy arrays? (★★☆)

Z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):
    print(index,value)
for index in np.ndindex(Z.shape):
        print(index,Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [192]:
#48. Generate a generic 2D Gaussian­like array (★★☆)
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma,mu = 1.0,0.0
G = np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)      

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [193]:
#49. How to randomly place p elements in a 2D array? (★★☆)
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace = False),1)    

In [195]:
#50. Subtract the mean of each row of a matrix (★★☆)# Author: Warren Weckesser
X = np.random.rand(5,10)# Recent versions of numpy
Y = X-X.mean(axis = 1,keepdims=True)# Older versions of numpy
Y = X-X.mean(axis = 1).reshape(-1,1) 
Y

array([[-0.46580823,  0.33341597,  0.47389293, -0.26468288,  0.42716847,
         0.26129579, -0.26233066, -0.09125536, -0.2693691 , -0.14232694],
       [-0.38567106,  0.49678276,  0.14433729,  0.28543564, -0.40824746,
         0.00855283,  0.14044616, -0.30938393,  0.05894589, -0.03119813],
       [ 0.55381303, -0.22166312, -0.16154936, -0.2899991 , -0.32826809,
        -0.0559067 , -0.20441181,  0.53299788, -0.03353044,  0.20851771],
       [-0.01649826,  0.36214383,  0.11513478, -0.02447806, -0.41472927,
        -0.39321515, -0.04670029,  0.26078685,  0.03258021,  0.12497535],
       [ 0.27690184,  0.31489952, -0.07477368,  0.2553104 ,  0.26958153,
        -0.1414909 , -0.25915651,  0.00413082, -0.33673461, -0.30866839]])

In [196]:
#51. How to I sort an array by the nth column? (★★☆)# Author: Steve Tjoa
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])      

[[4 9 5]
 [0 8 1]
 [6 7 9]]
[[6 7 9]
 [0 8 1]
 [4 9 5]]


In [197]:
#52. How to tell if a given 2D array has null columns? (★★☆)# Author: Warren Weckesser
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())      

False


In [198]:
#53. Find the nearest value from a given value in an array (★★☆)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print(m)      

0.5076043602987383


In [199]:
#54. Create an array class that has a name attribute

In [200]:
#class NamedArray(np.ndarray):
    #def__new__(cls,array,name="no name")
   # obj=np.asarray(array).view(cls)
    #obj.name=name
    #return obj
    #def__array_finalize__(self,obj)
    #if obj is None:return 
    #self.info=getattr(obj,'name',"no name")
#Z=NamedArray(np.arange(10),"range_10")
#print(Z.name)

In [201]:
#55. Consider a given vector, how to add 1 to each element indexed by a secondvector (be careful with repeated indices)? (★★★)# Author: Brett Olsen
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I,minlength=len(Z))
print(Z)

[1. 4. 2. 3. 3. 4. 3. 6. 3. 1.]


In [202]:
#56. How to accumulate elements of a vector (X) to an array (F) based on an index list(I)? (★★★)# Author: Alan G Isaac
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [203]:
#57. Considering a (w,h,3) image of (dtype=ubyte), compute the number of uniquecolors (★★★)# Author: Nadav Horesh
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256+I[...,1]*256+I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [204]:
#58. Considering a four dimensions array, how to get sum over the last two axis atonce? (★★★)
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2]+(-1,)).sum(axis=-1)
print(sum)

[[51 56 47 53]
 [42 53 33 67]
 [67 58 56 62]]


In [205]:
#59. Considering a one­dimensional vector D, how to compute means of subsets of Dusing a vector S of same size describing subset indices? (★★★)# Author: Jaime Fernández del Río
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S,weights = D)
D_counts = np.bincount(S)
D_means = D_sums/D_counts
print(D_means)

[0.51621061 0.5217955  0.32989765 0.47783591 0.53855411 0.48084149
 0.66542837 0.51309301 0.48327219 0.50348468]


In [206]:
#60. How to get the diagonal of a dot product? (★★★)# Author: Mathieu Blondel# Slow version
#np.diag(np.dot(A,B))# Fast version
#np.sum(A*B.T,axis=1)# Faster version
#np.einsum("ij,ji->i",A,B)

In [207]:
#61. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutivezeros interleaved between each value? (★★★)# Author: Warren WeckesserZ=np.array([1,2,3,4,5])
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z)+(len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [208]:
#62. Consider an array of dimension (5,5,3), how to mulitply it by an array withdimensions (5,5)? (★★★)
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [209]:
#63. How to swap two rows of an array? (★★★)# Author: Eelco Hoogendoorn
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [211]:
#64. Consider a set of 10 triplets describing 10 triangles (with shared vertices), 
#find the set of unique line segments composing all the triangles (★★★)# Author: Nicolas P. Rougier
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view(dtype=[('p0',F.dtype),('p1',F.dtype)])
G = np.unique(G)
print(G)

[( 3, 31) ( 3, 94) ( 5, 41) ( 5, 93) (18, 28) (18, 50) (18, 75) (18, 97)
 (19, 40) (19, 86) (26, 45) (26, 48) (27, 37) (27, 48) (27, 57) (27, 74)
 (28, 75) (31, 94) (37, 74) (40, 86) (41, 93) (45, 48) (48, 57) (50, 97)
 (51, 66) (51, 83) (60, 73) (60, 94) (66, 83) (73, 94)]


In [212]:
#65. Given an array C that is a bincount, how to produce an array A such thatnp.bincount(A) == C? (★★★)
# Author: Jaime Fernández del Río
C=np.bincount([1,1,2,3,4,4,6])
A=np.repeat(np.arange(len(C)),C)
print(A)

[1 1 2 3 4 4 6]


In [213]:
#66. How to compute averages using a sliding window over an array? (★★★)# Author: Jaime Fernández del Ríodef
def moving_average(a,n=3):
    ret=np.cumsum(a,dtype=float)
    ret[n:]=ret[n:]-ret[:-n]
    return ret[n-1:]/n
Z=np.arange(20)
print(moving_average(Z,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [214]:
#67. Consider a one­dimensional array Z, build a two­dimensional array whose firstrow is (Z[0],Z[1],Z[2]) 
#and each subsequent row is shifted by 1 (last row shouldbe (Z[­3],Z[­2],Z[­1]) (★★★)
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks 
def rolling(a,window):
    shape=(a.size-window+1,window)
    strides=(a.itemsize,a.itemsize)
    return stride_tricks.as_strided(a,shape=shape,strides=strides)
Z=rolling(np.arange(10),3)
print(Z)



[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [117]:
#68. How to negate a boolean, or to change the sign of a float inplace? (★★★)





In [215]:
#69. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how tocompute distance from p to each line i (P0[i],P1[i])? (★★★)
def distance(P0,P1,p):
    T=P1-P0
    L=(T**2).sum(axis=1)
    U=-((P0[:,0]-p[...,0])*T[:,0]+(P0[:,1]-p[...,1])*T[:,1])/L
    U=U.reshape(len(U),1)
    D=P0+U*T-p
    return np.sqrt((D**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(1,2))
print(distance(P0,P1,p))

[3.68053328 7.168036   6.99195871 1.01317211 8.84139752 8.85672988
 7.13231367 0.83715276 4.63389423 6.00461804]


In [216]:
#70. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, howto compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)# Author: Italmassov Kuanysh# based on distance function from previous question
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(10,2))
print(np.array([distance(P0,P1,p_i)for p_i in p]))

[[ 9.63354801  6.28720747  8.84560178  7.43841612  7.1105376  11.18430585
  12.10945053  6.298678    9.97006007  3.26680177]
 [13.40862761  8.65987289  8.00208045 13.1863683   6.47822506 16.69993235
  15.9136136   6.49721715 13.1381425   1.74808371]
 [ 8.90265479  1.90684704  1.53316675 14.81363725  2.95896592 17.0414993
  11.46395547  2.44089435  7.55666176  0.22886609]
 [ 4.1535801   2.52141983  4.3528812  10.70740408  5.91547862 12.65214123
   6.7118042   5.89381667  2.90854775  4.43559759]
 [ 1.51733638  2.75768993  5.86185738  5.13142521  3.68478637  1.51108418
   0.91993763  1.19303325  0.32276527 15.75997872]
 [ 5.63377599  9.74729637  5.05474844  1.86891473  7.06897851  0.24985108
   3.12601009  8.79288616  5.79834686 16.21333994]
 [ 1.56965309  5.39215427  7.12747626  9.47197577  8.72330373 11.0787588
   4.13691401  8.79632223  0.16775575  6.44793424]
 [ 8.4285984  13.398238    9.52353163  2.0234157  11.52495298  0.48779841
   5.89838451 13.14371186  9.01344746 17.76805352]
 [

In [217]:
#71. Consider an arbitrary array, write a function that extract a subpart with a fixedshape and centered on a given element (pad with a fill value when necessary)(★★★)# Author: Nicolas Rougier
Z=np.random.randint(0,10,(10,10))
shape=(5,5)
fill=0
position=(1,1)
R=np.ones(shape,dtype=Z.dtype)*fill
P=np.array(list(position)).astype(int)
Rs=np.array(list(R.shape)).astype(int)
Zs=np.array(list(Z.shape)).astype(int)
R_start=np.zeros((len(shape),)).astype(int)
R_stop=np.array(list(shape)).astype(int)
Z_start=(P-Rs//2)
Z_stop=(P+Rs//2)+Rs%2
R_start=(R_start-np.minimum(Z_start,0)).tolist()
Z_start=(np.maximum(Z_start,0)).tolist()
R_stop=np.maximum(R_start,(R_stop-np.maximum(Z_stop-Zs,0))).tolist()
Z_stop=(np.minimum(Z_stop,Zs)).tolist()
r=[slice(start,stop) for start,stop in zip(R_start,R_stop)]
z=[slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r]=Z[z]
print(Z)
print(R)

[[8 1 4 3 8 9 2 0 8 1]
 [2 2 8 8 7 5 5 2 0 6]
 [6 6 5 5 0 6 5 5 6 6]
 [3 1 8 0 2 0 1 6 7 6]
 [4 3 4 7 8 1 1 7 7 4]
 [1 6 8 6 8 7 8 5 9 9]
 [5 8 4 4 9 7 3 0 1 3]
 [5 7 9 6 3 4 7 0 6 7]
 [2 2 1 2 4 1 4 4 1 3]
 [1 4 0 1 4 7 4 6 0 1]]
[[0 0 0 0 0]
 [0 8 1 4 3]
 [0 2 2 8 8]
 [0 6 6 5 5]
 [0 3 1 8 0]]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:20: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [218]:
#72. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate anarray R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)# Author: Stefan van der Walt
Z=np.arange(1,15,dtype=uint32)
R=stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [220]:
#73. Compute a matrix rank (★★★)# Author: Stefan van der Walt
Z=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(Z)
# Singular Value Decomposition
rank=np.sum(S>1e-10)
rank

10

In [221]:
#74. How to find the most frequent value in an array?
Z=np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


In [222]:
#75. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)# Author: Chris Barker
Z=np.random.randint(0,5,(10,10))
n=3
i=1+(Z.shape[0]-3)
j=1+(Z.shape[1]-3)
C=stride_tricks.as_strided(Z,shape=(i,j,n,n),strides=Z.strides+Z.strides)
print(C)

[[[[4 2 4]
   [2 4 0]
   [2 3 3]]

  [[2 4 2]
   [4 0 2]
   [3 3 1]]

  [[4 2 1]
   [0 2 1]
   [3 1 3]]

  [[2 1 4]
   [2 1 4]
   [1 3 4]]

  [[1 4 4]
   [1 4 1]
   [3 4 0]]

  [[4 4 0]
   [4 1 1]
   [4 0 0]]

  [[4 0 0]
   [1 1 3]
   [0 0 3]]

  [[0 0 3]
   [1 3 2]
   [0 3 3]]]


 [[[2 4 0]
   [2 3 3]
   [3 4 4]]

  [[4 0 2]
   [3 3 1]
   [4 4 4]]

  [[0 2 1]
   [3 1 3]
   [4 4 1]]

  [[2 1 4]
   [1 3 4]
   [4 1 1]]

  [[1 4 1]
   [3 4 0]
   [1 1 1]]

  [[4 1 1]
   [4 0 0]
   [1 1 3]]

  [[1 1 3]
   [0 0 3]
   [1 3 4]]

  [[1 3 2]
   [0 3 3]
   [3 4 3]]]


 [[[2 3 3]
   [3 4 4]
   [4 4 1]]

  [[3 3 1]
   [4 4 4]
   [4 1 3]]

  [[3 1 3]
   [4 4 1]
   [1 3 1]]

  [[1 3 4]
   [4 1 1]
   [3 1 4]]

  [[3 4 0]
   [1 1 1]
   [1 4 0]]

  [[4 0 0]
   [1 1 3]
   [4 0 2]]

  [[0 0 3]
   [1 3 4]
   [0 2 4]]

  [[0 3 3]
   [3 4 3]
   [2 4 0]]]


 [[[3 4 4]
   [4 4 1]
   [1 4 0]]

  [[4 4 4]
   [4 1 3]
   [4 0 3]]

  [[4 4 1]
   [1 3 1]
   [0 3 1]]

  [[4 1 1]
   [3 1 4]
   [3 1 3]]

  [[1 1 1]
   

In [223]:
#76. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices
#class Symetric(np.ndarray):
    #def__setitem__(self,(i,j),value)
    #super(Symetric,self).__setitem__((i,j),value)
    #super(Symetric,self).__setitem__((j,i),value)
#def symetric(Z):
    #return np.asarray(Z+Z.T-np.diag(Z.diagonal())).view(Symetric)
#S=symetric(np.random.randint(0,10,(5,5)))
#S[2,3]=42
#print(S)

In [136]:
#77. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape(n,1). How to compute the sum of of the p matrix products at once? (result hasshape (n,1)) (★★★)# Author: Stefan van der Walt
p,n=10,20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
S=np.tensordot(M,V,axes=[[0,2],[0,1]])
print(S)# It works, because:# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [224]:
#78. Consider a 16x16 array, how to get the block­sum (block size is 4x4)? (★★★)# Author: Robert Kern
#Z=np.ones(16)
#k=4
#S=np.add.reduceat(np.add.reduceat(Z,np.arange(0,Z.shape[0],k),axis=0),np.arange(0,Z.shape[1],k),axis=1)

In [225]:
#79. How to implement the Game of Life using numpy arrays? (★★★)# Author: Nicolas Rougier
def iterate(Z):# Count neighbours
# Count neighbours 
    N=(Z[0:-2,0:-2]+Z[0:-2,1:-1]+Z[0:-2,2:]+
       Z[1:-1,0:-2]             +Z[1:-1,2:]+
       Z[2:,0:-2]+Z[2:,1:-1]+Z[2:,2:])# Apply rules
    birth=(N==3)&(Z[1:-1,1:-1]==0)
    survive=((N==2)|(N==3))&(Z[1:-1,1:-1]==1)
    Z[...]=0
    Z[1:-1,1:-1][birth|survive]=1
    return Z
Z=np.random.randint(0,2,(50,50))
for i in range(100):
    Z=iterate(Z)

In [226]:
Z

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [227]:
#80. How to get the n largest values of an array (★★★)
Z=np.arange(10000)
np.random.shuffle(Z)
n=5# Slow
print(Z[np.argsort(Z)[-n:]])
# Fast
print(Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9996 9999 9997 9995]


In [231]:
#81. Given an arbitrary number of vectors, build the cartesian product (everycombinations of every item) (★★★)
# Author: Stefan Van der Walt

#def cartesian(arrays):
   # arrays=[np.asarray(a)for a in arrays]
    #shape=(len(x)for x in arrays)
    #ix=np.indices(shape,dtype=int)
    #ix=ix.reshape(len(arrays),-1).T
    #for n,arr in enumerate(arrays):
        #ix[:,n]=arrays[n][ix[:,n]]
       # return ix 
#print(cartesian([1,2,3],[4,5],[6,7]))

In [233]:
#82. How to create a record array from a regular array? (★★★)
Z=np.array([("Hello",2.5,3),("World",3.6,2)])
R=np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats='S8, f8, i8')
R

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

In [241]:
#83. Consider a large vector Z, compute Z to the power of 3 using 3 different methods(★★★)Author:Ryan
#x=np.random.rand(5e7)
#%time it np.power(x,3)
#1 loops,best of 3:574 ms per loop
#%time it x*x*x
#1 loops,best of 3:429 ms per loop
#%time it np.einsum('i,i,i->i',x,x,x)
#1 loops,best of 3:244 ms per loop(★★★)# Author: Gabe Schwartz

In [242]:
#84. Consider two arrays A and B of shape (8,3) and (2,2). 
#How to find rows of A thatcontain elements of each row of B regardless of the order of the elements in B?

A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[...,np.newaxis,np.newaxis]==B)
rows=(C.sum(axis=(1,2,3))>=B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 5 6 7]


In [243]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[...,np.newaxis,np.newaxis]==B)
rows=(C.sum(axis=(1,2,3))>=B.shape[1]).nonzero()[0]
print(rows)

[0 5 7]


In [244]:
#85. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)# Author: Robert Kern

Z=np.random.randint(0,5,(10,3))
E=np.logical_and.reduce(Z[:,1:]==Z[:,:-1],axis=1)
U=Z[~E]
print(Z)
print(U)

[[2 1 1]
 [1 2 3]
 [4 1 4]
 [0 2 2]
 [0 2 1]
 [0 2 2]
 [1 2 1]
 [1 0 0]
 [4 0 0]
 [3 0 2]]
[[2 1 1]
 [1 2 3]
 [4 1 4]
 [0 2 2]
 [0 2 1]
 [0 2 2]
 [1 2 1]
 [1 0 0]
 [4 0 0]
 [3 0 2]]


In [245]:
#86. Convert a vector of ints into a matrix binary representation (★★★)# Author: Warren Weckesser

I=np.array([0,1,2,3,15,16,32,64,128])
B=((I.reshape(-1,1)&(2**np.arange(8)))!=0).astype(int)

print(B[:,::-1])# Author: Daniel T. McDonald
I=np.array([0,1,2,3,15,16,32,64,128],dtype=np.uint8)
print(np.unpackbits(I[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [246]:
#87. Given a two dimensional array, how to extract unique rows? (★★★)# Author: Jaime Fernández del Río

#Z=np.random.randint(0,2,(6,3))
#T=np.ascontiguousarray(Z).view(np.dtype((np.void,Z.dtype.itemsize*Z.shape[1]))),idx=np.unique(T,return_index=True)
#uZ=Z[idx]
#print(uZ)

In [248]:
#88. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum,and mul function (★★★)
# Author: Alex Riley# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

#np.einsum('i->',A)# np.sum(A)
#np.einsum('i,i->i',A,B)# A * B
#np.einsum('i,i',A,B)# np.inner(A, B)
#np.einsum('i,j',A,B)# np.outer(A, B)

In [249]:
#89. Considering a path described by two vectors (X,Y), how to sample it usingequidistant samples (★★★)?
# Author: Bas Swinckels
phi=np.arange(0,10*np.pi,0.1)
a=1
x=a*phi*np.cos(phi)
y=a*phi*np.sin(phi)
dr=(np.diff(x)**2+np.diff(y)**2)**.5# segment lengths

r=np.zeros_like(x)
r[1:]=np.cumsum(dr)# integrate path
r_int=np.linspace(0,r.max(),200)# regular spaced path
x_int=np.interp(r_int,r,x)# integrate path
y_int=np.interp(r_int,r,y)

In [251]:
r_int

array([  0.        ,   2.48788858,   4.97577716,   7.46366574,
         9.95155432,  12.43944289,  14.92733147,  17.41522005,
        19.90310863,  22.39099721,  24.87888579,  27.36677437,
        29.85466295,  32.34255152,  34.8304401 ,  37.31832868,
        39.80621726,  42.29410584,  44.78199442,  47.269883  ,
        49.75777158,  52.24566016,  54.73354873,  57.22143731,
        59.70932589,  62.19721447,  64.68510305,  67.17299163,
        69.66088021,  72.14876879,  74.63665736,  77.12454594,
        79.61243452,  82.1003231 ,  84.58821168,  87.07610026,
        89.56398884,  92.05187742,  94.539766  ,  97.02765457,
        99.51554315, 102.00343173, 104.49132031, 106.97920889,
       109.46709747, 111.95498605, 114.44287463, 116.9307632 ,
       119.41865178, 121.90654036, 124.39442894, 126.88231752,
       129.3702061 , 131.85809468, 134.34598326, 136.83387184,
       139.32176041, 141.80964899, 144.29753757, 146.78542615,
       149.27331473, 151.76120331, 154.24909189, 156.73

In [252]:
x_int

array([ 0.00000000e+00, -3.73131229e-01, -2.59817608e+00, -3.26212050e+00,
       -2.18442687e+00, -2.98929946e-02,  2.42923642e+00,  4.54913599e+00,
        5.92318348e+00,  6.35117933e+00,  5.82369277e+00,  4.46259540e+00,
        2.47320794e+00,  1.09577220e-01, -2.36575300e+00, -4.71261671e+00,
       -6.72701769e+00, -8.25541575e+00, -9.18486120e+00, -9.46381505e+00,
       -9.11085788e+00, -8.12875279e+00, -6.63306046e+00, -4.69271059e+00,
       -2.44736165e+00, -2.05444585e-02,  2.46101146e+00,  4.86841760e+00,
        7.08937968e+00,  9.02539126e+00,  1.05948609e+01,  1.17357250e+01,
        1.24068974e+01,  1.25885805e+01,  1.22815267e+01,  1.15053927e+01,
        1.02963689e+01,  8.70429550e+00,  6.78948686e+00,  4.61716636e+00,
        2.25853448e+00, -1.98731680e-01, -2.68040566e+00, -5.11543300e+00,
       -7.41973991e+00, -9.53891040e+00, -1.14237629e+01, -1.29919305e+01,
       -1.42355069e+01, -1.51243232e+01, -1.56061571e+01, -1.57219415e+01,
       -1.54217066e+01, -

In [253]:
y_int

array([ 0.00000000e+00,  1.74026724e+00,  9.81816584e-01, -1.34251287e+00,
       -3.53191891e+00, -4.70449474e+00, -4.59573427e+00, -3.33831870e+00,
       -1.28956083e+00,  1.14234685e+00,  3.55645601e+00,  5.62188218e+00,
        7.09389488e+00,  7.82951803e+00,  7.78700678e+00,  6.99685666e+00,
        5.55535240e+00,  3.60417006e+00,  1.30506373e+00, -1.15819722e+00,
       -3.61328132e+00, -5.89130465e+00, -7.87065053e+00, -9.41689057e+00,
       -1.04714836e+01, -1.09903787e+01, -1.09354306e+01, -1.03330912e+01,
       -9.22690166e+00, -7.67489830e+00, -5.75257980e+00, -3.54832201e+00,
       -1.15854355e+00,  1.31709956e+00,  3.78023622e+00,  6.13780326e+00,
        8.30540149e+00,  1.02098724e+01,  1.17910419e+01,  1.29972950e+01,
        1.37774249e+01,  1.41319792e+01,  1.40585758e+01,  1.35636816e+01,
        1.26345244e+01,  1.13409083e+01,  9.72216360e+00,  7.79464305e+00,
        5.64544223e+00,  3.32503222e+00,  8.88107041e-01, -1.59329248e+00,
       -4.05992507e+00, -

In [254]:
#90. Given an integer n and a 2D array X, select from X 
#the rows which can be interpreted as draws from a multinomial distribution with n degrees,
#i.e., the rows which only contain integers and which sum to n. (★★★)


# Author: Evgeni Burovski

X=np.asarray([[1.0,0.0,3.0,8.0],[2.0,0.0,1.0,1.0],[1.5,2.5,1.0,0.0]])
n=4
M=np.logical_and.reduce(np.mod(X,1)==0,axis=-1)
M&=(X.sum(axis=-1)==n)
print(X[M])

[[2. 0. 1. 1.]]


In [ ]:
# Author: Evgeni BurovskiX=np.asarray([[1.0,0.0,3.0,8.0],[2.0,0.0,1.0,1.0],[1.5,2.5,1.0,0.0]])n=4M=np.logical_and.reduce(np.mod(X,1)==0,axis=-1)M&=(X.sum(axis=-1)==n)print(X[M])