In [1]:
#1.import python packages and create a Data Frame random integer numbers
import pandas as pd
import numpy as np
data = np.random.randint(1,100,(10,5))
df = pd.DataFrame(data = data,columns = list("ABCDE"))
print(df)

    A   B   C   D   E
0  89  64  34  51  47
1  87  37  79  72  14
2  98  47  84  82   8
3  58  33  67   6  74
4  45  76  28  21  26
5  46  61  29  95  75
6  31  68  10  46  42
7  80  60  31  24  75
8  97  88  84  74  10
9  20  34  16  40  51


In [2]:
df

A   B   C   D   E
0  89  64  34  51  47
1  87  37  79  72  14
2  98  47  84  82   8
3  58  33  67   6  74
4  45  76  28  21  26
5  46  61  29  95  75
6  31  68  10  46  42
7  80  60  31  24  75
8  97  88  84  74  10
9  20  34  16  40  51

In [3]:
#2. create a numpy array from the data frame
df_np = df.to_numpy()

In [4]:
df_np

array([[89, 64, 34, 51, 47],
       [87, 37, 79, 72, 14],
       [98, 47, 84, 82,  8],
       [58, 33, 67,  6, 74],
       [45, 76, 28, 21, 26],
       [46, 61, 29, 95, 75],
       [31, 68, 10, 46, 42],
       [80, 60, 31, 24, 75],
       [97, 88, 84, 74, 10],
       [20, 34, 16, 40, 51]])

In [5]:
print(df_np)

[[89 64 34 51 47]
 [87 37 79 72 14]
 [98 47 84 82  8]
 [58 33 67  6 74]
 [45 76 28 21 26]
 [46 61 29 95 75]
 [31 68 10 46 42]
 [80 60 31 24 75]
 [97 88 84 74 10]
 [20 34 16 40 51]]


In [6]:
#3. View top few rows of the data frame
df.head()

A   B   C   D   E
0  89  64  34  51  47
1  87  37  79  72  14
2  98  47  84  82   8
3  58  33  67   6  74
4  45  76  28  21  26

In [7]:
print(df.head())

    A   B   C   D   E
0  89  64  34  51  47
1  87  37  79  72  14
2  98  47  84  82   8
3  58  33  67   6  74
4  45  76  28  21  26


In [8]:
#4. View top 2 rows of the data frame
print(df.head(2))

    A   B   C   D   E
0  89  64  34  51  47
1  87  37  79  72  14


In [9]:
#5. view last 3 rows of the data frame
print(df.tail(3))

    A   B   C   D   E
7  80  60  31  24  75
8  97  88  84  74  10
9  20  34  16  40  51


In [10]:
#6. Get the value at 8 th row and 2 nd column
print(df.iloc[7,1])

60


In [11]:
#7. Set value at 8 th row and 2 nd column
df.iat[7,1]=-9999

In [12]:
print(df)

    A     B   C   D   E
0  89    64  34  51  47
1  87    37  79  72  14
2  98    47  84  82   8
3  58    33  67   6  74
4  45    76  28  21  26
5  46    61  29  95  75
6  31    68  10  46  42
7  80 -9999  31  24  75
8  97    88  84  74  10
9  20    34  16  40  51


In [13]:
df.idxmax()

A    2
B    8
C    2
D    5
E    5
dtype: int64

In [14]:
df.idxmin()

A    9
B    7
C    6
D    3
E    2
dtype: int64

In [15]:
#8. Copy the data from one data frame to another
df1 = df.copy()
print(df1)

    A     B   C   D   E
0  89    64  34  51  47
1  87    37  79  72  14
2  98    47  84  82   8
3  58    33  67   6  74
4  45    76  28  21  26
5  46    61  29  95  75
6  31    68  10  46  42
7  80 -9999  31  24  75
8  97    88  84  74  10
9  20    34  16  40  51


In [16]:
#9. Find out values from data frame which are more than 50
print(df[df>50])

      A     B     C     D     E
0  89.0  64.0   NaN  51.0   NaN
1  87.0   NaN  79.0  72.0   NaN
2  98.0   NaN  84.0  82.0   NaN
3  58.0   NaN  67.0   NaN  74.0
4   NaN  76.0   NaN   NaN   NaN
5   NaN  61.0   NaN  95.0  75.0
6   NaN  68.0   NaN   NaN   NaN
7  80.0   NaN   NaN   NaN  75.0
8  97.0  88.0  84.0  74.0   NaN
9   NaN   NaN   NaN   NaN  51.0


In [17]:
#10. Set all the values in data frame as -5555 when value is more than 50

df[df>50] = -5555
print(df)

      A     B     C     D     E
0 -5555 -5555    34 -5555    47
1 -5555    37 -5555 -5555    14
2 -5555    47 -5555 -5555     8
3 -5555    33 -5555     6 -5555
4    45 -5555    28    21    26
5    46 -5555    29 -5555 -5555
6    31 -5555    10    46    42
7 -5555 -9999    31    24 -5555
8 -5555 -5555 -5555 -5555    10
9    20    34    16    40 -5555
